schema: ./server/src/schema/**/*.graphql
documents: ./client/src/graphql/**/*.graphql
extensions:
  codegen:
    generates:
      ./client/src/generated-types.tsx:
        config:
          skipDocumentsValidation: true
          withComponent: false
          withHOC: false
          withHooks: true
        plugins:
          - add: '/* tslint:disable */'
          - typescript
          - typescript-operations
          - typescript-react-apollo
      ./server/src/generated-types.ts:
        config:
          contextType: '@graphback/runtime#GraphbackRuntimeContext'
          mappers:
            Comment: ./generated-db-types#comment
            Note: ./generated-db-types#note
          skipDocumentsValidation: true
          useIndexSignature: true
        plugins:
          - add: '/* tslint:disable */'
          - typescript
          - typescript-resolvers
  dbmigrations:
    client: pg
    connection:
      database: users
      host: localhost
      password: postgres
      port: 55432
      user: postgresql
  diff:
    baseSchema: your-base-schema-here
  graphback:
    crud:
      create: true
      delete: true
      find: true
      findAll: true
      subCreate: true
      subDelete: true
      subUpdate: true
      update: true
    model: ./model
    plugins:
      graphback-client:
        format: graphql
        outputPath: ./client/src/graphql
      graphback-resolvers:
        format: ts
        outputPath: ./server/src/resolvers
      graphback-schema:
        format: graphql
        outputPath: ./server/src/schema
